clients/urls.py
from django.urls import path
from . import views 

app_name = 'clients'

urlpatterns = [
    path('', views.ClientListView, name='clients'),    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('solutions/', include('solutions.urls')),
    path('clients/', include('clients.urls')),
    path('publications/', include('publications.urls')),
    path('tools/', include('tools.urls')),
    path('', include('generals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

generals/urls.py
from django.urls import path
# from django.views.generic.base import TemplateView
from . import views

app_name = 'generals'

urlpatterns = [
    path('contact-us/', views.ContactUsView, name='contact_us'),
    path('about-us/', views.about, name='about_us'),
    path('tags/<str:tag_slug>/', views.TagListView, name='tags'),
    path('', views.HomeView, name='home'),
]

publications/urls.py
from django.urls import path
from . import views 

app_name = 'publications'

urlpatterns = [
    path('', views.PublicationsView, name='publications'),
]

solutions/urls.py
from django.urls import path
from . import views 

app_name = 'solutions'

urlpatterns = [
    path('', views.SolutionsView, name='solutions'),
    # path('details/', views.SolutionDetailsView, name='solution_details'), #should be removed
    path('<str:slug>/', views.SolutionView, name='solution'),
]

templates/components/_footer.html
{% load i18n static %}

<div class="fbox">
    <div class="fleft">
        <img src="{% static 'generals/img/Alast-Logo-green-dark.jpg' %}" alt="">
    </div>

    <nav>
        <a href="{% url 'solutions:solutions' %}" class="{% if page_title == 'Solutios' %}active{% endif %}">{% trans "Solutions" %}</a>
        <a href="{% url 'publications:publications' %}" class="{% if page_title == 'Publications' %}active{% endif %}">{% trans "Publications" %}</a>
        <a href="{% url 'clients:clients' %}" class="{% if page_title == 'Clients' %}active{% endif %}">{% trans "Clients" %}</a>
        <br>
        <a href="{% url 'generals:about_us' %}" class="{% if page_title == 'About us' %}active{% endif %}">{% trans "About us" %}</a>
        <a href="{% url 'generals:contact_us' %}" class="{% if page_title == 'Contact us' %}active{% endif %}">{% trans "Contact us" %}</a>
    </nav>

    <nav>
    <p>
        {% comment %} 
        <!-- Farsi version for future -->
        شرکت بهین آفرینش الست (استودیو طراحی الست) افتخار دارد ارائه دهنده خدمات متنوع دیزاین به صنعت و جامعه باشد:
        خدمات طراحی استودیو طراحی عبارتند از: طراحی صنعتی محصولات فیزیکال و دیجیتال، UI/UX، طراحی بسته بندی، طراحی
        مبلمان شهری، طراحی داخلی، طراحی خدمات و PSS، طراحی خدمات و طراحی گرافیک و گرافیک صنعتی،
        {% endcomment %}
        
        Behin Afrainesh Alast Company (Alast Design Studio) is the provider of various design services including:
        Physical and Digital Product Design & UI/UX, Packaging Design, Urban Furniture Design, Interior Design,
        Service Design, PSS Design, Graphic and Industrial Graphic Design.
    </p>
    </nav>
    {% comment %}

    <nav>
        <a href="{% url 'generals:home' %}">Addresses</a>
        <a href="{% url 'solutions:solutions' %}">generals</a>
        <a href="{% url 'solutions:solutions' %}">gitignore</a>
        <a href="{% url 'publications:publications' %}">Subscribe</a>
        <a href="{% url 'generals:home' %}">Addresses</a>
        <a href="{% url 'solutions:solutions' %}">Social medias</a>
        <a href="{% url 'publications:publications' %}">Branches</a>
    </nav>
    {% endcomment %}
</div>

templates/components/_header.html
{% load i18n static %}

<div>
    <a href="{% url 'generals:home' %}">
        <img src="{% static 'generals/img/Alast-Logo-green-dark.jpg' %}" alt="Alast Design Studio logo" id="logo">
        <span>{% trans "Alast Design Studio" %}</span>
    </a>

    <nav>
        <a href="{% url 'generals:home' %}" class="{% if page_title == 'Home' %} active {% endif %}">{% trans "Home" %}</a>
        <a href="{% url 'solutions:solutions' %}" class="{% if page_title == 'Solutios' %} active {% endif %}">{% trans "Solutions" %}</a>
        <a href="{% url 'publications:publications' %}" class="{% if page_title == 'Publications' %} active {% endif %}">{% trans "Publications" %}</a>
        <a href="{% url 'clients:clients' %}" class="{% if page_title == 'Clients' %} active {% endif %}">{% trans "Clients" %}</a>
        <a href="{% url 'generals:about_us' %}" class="{% if page_title == 'About us' %} active {% endif %}">{% trans "About us" %}</a>
        <a href="{% url 'generals:contact_us' %}" class="{% if page_title == 'Contact us' %} active {% endif %}">{% trans "Contact us" %}</a>
    </nav>

    <button onclick="openNav()">|||</button>
</div>

templates/components/_show_awards.html
<h2 class="main-title">
    <span>
       <span class="mil-thin">Our</span>
    </span>awards
 </h2>
 <div class="award_box">
    {% for award in awards %}
    <div class="award">
       <img src="{{ award.image.url }}">
       <div>
          <h5>{{ award.title }}</h5>
          <h4>{{ award.year }}</h4>
          {% if award.description %}
          <h4>{{ award.description }}</h4>
          {% endif %}
       </div>
    </div>
    {% endfor %}     
 </div>

templates/components/_show_team_members.html
{% load static %}

<h2 class="main-title">
    <span>team
       <span class="mil-thin">members</span>
    </span>
</h2>
<div class="team_box">
    {% for member in team_members %}
    <div class="member">
        <img src="{{ member.avatar.url }}" alt="">
        <div class="member_over">
            <a href="#">{{ member.user }}</a>
            <span>{{ member.role }}</span>
            <div class="member_socials">
            {% if member.instagram %}
            <a href="{{ member.instagram }}">
                <img src="{% static 'assets/logos/instagram.png' %}" alt="instagram logo" height="16px" width="auto"></a>              
            {% endif %}
            {% if member.linkedin %}
            <a href="{{ member.linkedin }}">
                <img src="{% static 'assets/logos/linkedin.png' %}" alt="linkedin logo" height="16px" width="auto"></a>              
            {% endif %}
            {% if member.behance %}
            <a href="{{ member.behance }}">
                <img src="{% static 'assets/logos/behance.png' %}" alt="behance logo" height="16px" width="auto"></a>              
            {% endif %}
            {% if member.dribbble %}
            <a href="{{ member.dribbble }}">
                <img src="{% static 'assets/logos/dribbble.png' %}" alt="dribbble logo" height="16px" width="auto"></a>              
            {% endif %}
            {% if member.twitter %}
            <a href="{{ member.twitter }}">
                <img src="{% static 'assets/logos/twitter.png' %}" alt="twitter logo" height="16px" width="auto"></a>              
            {% endif %}
        
            
            {% if member.link %}
            <a href="{{ member.link }}">
                <img src="{% static 'assets/logos/link.png' %}" alt="link logo" height="16px" width="auto"></a>              
            {% endif %}
        
            </div>
        </div>
    </div>
    {% endfor %}     
</div>

templates/components/_slider.html
<!-- slider -->
<img src="https://placehold.co/1800x400" alt="">