clients/urls.py
from django.urls import path
from . import views 

app_name = 'clients'

urlpatterns = [
    path('', views.ClientListView, name='clients'),    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('solutions/', include('solutions.urls')),
    path('clients/', include('clients.urls')),
    path('publications/', include('publications.urls')),
    path('tools/', include('tools.urls')),
    path('', include('generals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

generals/urls.py
from django.urls import path
# from django.views.generic.base import TemplateView
from . import views

app_name = 'generals'

urlpatterns = [
    path('contact-us/', views.ContactUsView, name='contact_us'),
    path('about-us/', views.about, name='about_us'),
    path('tags/<str:tag_slug>/', views.TagListView, name='tags'),
    path('', views.HomeView, name='home'),
]

solutions/urls.py
from django.urls import path
from . import views 

app_name = 'solutions'

urlpatterns = [
    path('', views.SolutionsView, name='solutions'),
    # path('details/', views.SolutionDetailsView, name='solution_details'), #should be removed
    path('<str:slug>/', views.SolutionView, name='solution'),
]

solutions/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from taggit.managers import TaggableManager

from tools.models import TimeStampedModel, ActiveManager
from tools.make_thumbnail import make_thumbnail
from clients.models import Client


class SolutionCategory(TimeStampedModel):
    parent = models.ForeignKey(
        'self', 
        on_delete=models.SET_NULL, 
        verbose_name=_("Parent"),
        null=True, 
        blank=True, 
    )
    name = models.CharField(
        _("Name"),
        max_length=250,
        unique=True,
    )
    slug = models.SlugField(
        _("Slug"),
        allow_unicode=True        
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)
    

class Solution(TimeStampedModel):
    title = models.CharField(
        _("Title"),        
        max_length=255,
        unique=True
    )
    slug = models.SlugField(
        _("Slug"),
        allow_unicode=True
    )
    category = models.ForeignKey(
        SolutionCategory, 
        on_delete=models.SET_NULL,
        verbose_name=_("Category"),
        related_name='solutions',
        null=True, 
        blank=True, 
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        verbose_name=_("Client"),
        related_name='solutions',
        null=True,
        blank=True
    )
    product_model = models.CharField(
        _("Product model"),
        max_length=150,
        null=True,
        blank=True
    )
    design_date = models.CharField(
        _("Design date"),
        max_length=150,
        null=True,
        blank=True
    )
    designer = models.CharField(
        _("Designer"),
        max_length=150,
        null=True,
        blank=True
    )
    manufacturing_methods = models.CharField(
        _("Manufacturing methods"),
        max_length=150,
        null=True,
        blank=True
    )
    description = models.TextField(
        _("Description"),
    )
    cover_image = models.ImageField(
        _("Cover image"),
        upload_to='solutions/cover_images/'
    )
    thumbnail = models.ImageField(
        upload_to='solutions/thumbnails/',
        null=True,
        blank=True
    )
    tags = TaggableManager(
        _("Tags"),        
        blank=True
    )
    active = models.BooleanField(
        _("Active"),
        default=True,
    )
    objects = models.Manager()
    actives = ActiveManager()
    # client = mdoels.CharField(null=True, blank=True)
    # client_logo = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title
        

    def save(self, *args, **kwargs):
        self.thumbnail = make_thumbnail(self.cover_image.file)
        self.slug = slugify(self.title, allow_unicode=True)
        return super().save(*args, **kwargs)
    

class Award(TimeStampedModel):
    title = models.CharField(
        _("Title"),
        max_length=250,
    )
    year = models.PositiveSmallIntegerField(
        default=2024
    )
    description = models.TextField(
        _("Description"),
        blank=True
    )
    image = models.ImageField(
        _("Image"),
        upload_to='awards/'
    )

    def __str__(self):
        return self.title
    

solutions/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.db.models import Prefetch, Count, Q

from .models import Solution, SolutionCategory

def SolutionsView(request):
    solutions = Solution.actives.all()
    
    categories = SolutionCategory.objects.annotate(
    active_solution_count=Count('solutions', filter=Q(solutions__in=solutions))
        ).filter(active_solution_count__gt=0).prefetch_related(Prefetch('solutions', queryset=solutions))
    context = dict(
        page_title=_("Solutios"),
        # solutions=solutions,
        categories=categories,
        crumbs=[(_("Solutions"), None)]
    )
    
    return render(
        request,
        'solutions/solutions.html',
        context
    )

def SolutionView(request, slug):    
    solution = get_object_or_404(Solution, slug=slug, active=True)
    context = dict(
        page_title=_("Solution"),
        solution=solution,
        crumbs=[
            (_("Solutions"), 'solutions:solutions'),
            (solution.title, None),
            ]
    )    
    return render(
        request,
        'solutions/solution.html',
        context
    )

# should be removed
# def SolutionDetailsView(request):
#     context = dict(
#         page_title=_("Solution"),
#     )
    
#     return render(
#         request,
#         'solutions/solution_details.html',
#         context
#     )

templates/solutions/_solution_card.html
{% load i18n static %}

<div class="solution">
	<div class="sol_img">
		<a href="{% url 'solutions:solution' solution.slug %}">
		   {% if solution.cover_image %}		   
		   <img src="{{ solution.cover_image.url }}" alt="{{ solution.title }}">        
		   {% endif %}
		</a>
	</div>

	<div>
		<div class="sol_top">
			<a href="{% url 'solutions:solution' solution.slug %}">
				<h4>{{ solution.title }}</h4>
			</a>
			<span>{{ solution.category }}</span>
		</div>
		
		<p>{{ solution.description | truncatewords:5 }}</p>

		<a href="{% url 'solutions:solution' solution.slug %}" class="btn btn-white no-rm">More details<img src="{% static 'assets/g1b.svg' %}"></a>
	</div>
</div>

templates/solutions/solution.html
{% extends "_base.html" %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<main class="main_solution">

	<h1 class="main-title">
		<span>{{ solution.title }}
		   <!-- <span class="mil-thin"></span> -->
		</span>
	</h1>

    <div class="s-base">
		<div class="s-left">
			<div>
				{% if solution.client %}
				<div class="sinfo">
					<span>{% trans "Client" %}:</span>
					{{ solution.client }}
				</div>
				{% endif %}

				{% if solution.designer %}</span>
				<div class="sinfo">
					<span>{% trans "Designer" %}</span>
					{{ solution.designer }}           
				</div>
				{% endif %}

				{% if solution.design_date %}
				<div class="sinfo">
					<span>{% trans "Design date" %}</span>
					{{ solution.design_date }}           
				</div>
				{% endif %}

				{% if solution.design_date %}
				<div class="sinfo">
					<span>{% trans "Design date" %}</span>
					{{ solution.design_date }}           
				</div>
				{% endif %}

				{% if solution.product_model %}
				<div class="sinfo">
					<span>{% trans "Product model" %}</span>
					{{ solution.product_model }}           
				</div>
				{% endif %}

				{% if solution.manufacturing_methods %}
				<div class="sinfo">
					<span>{% trans "Manufacturing methods" %}</span>
					{{ solution.manufacturing_methods }}           
				</div>
				{% endif %}
			</div>

			<h3>{% trans "Project description" %}</h3>
			<p>{{ solution.description | linebreaksbr }}</p>

			<!-- {% if solution.tags %} -->
			<div class="stags">
				{% for tag in solution.tags.all %}
				<a href="{% url 'generals:tags' tag.slug %}"><span>{{ tag.name }}</span></a>            
				{% endfor %} 
				{% comment %}				  
				<a href="{% url 'generals:tags' tag.slug %}" style="border: 1px solid; border-radius: 10px; padding: 2px 6px; color: white; background-color: #42ae70; margin: 5px;"><span>{{ tag.name }}</span></a>            
				<a href="#"><span>firstTag</span></a>
				<a href="#"><span>secorstTag</span></a>
				<a href="#"><span>sdftTag</span></a>
				<a href="#"><span>sfsdfsd-ag</span></a>
				<a href="#"><span>secortTag</span></a>
				{% endcomment %}
			</div>
			<!-- {% endif %} -->
		</div>

		<div class="s-right">
			{% if solution.cover_image %}
				<img src="{{ solution.cover_image.url }}" alt="">
			{% endif %}

			{% if solution.images.all %}
				<!-- <h3>{% trans "Project gallery" %}</h3> -->
				{% for item in solution.images.all %}
					<!-- <a href="{{ item.file.url }}" target="_blank"> -->
					<img src="{{ item.file.url }}" alt="item.title">
					<!-- </a>
					<br>
					{% if item.title %}
					{{ item.title }}
					{% endif %} -->
				{% endfor %}			
			{% endif %}
		</div>
    </div>
   
	

    {% comment %}
	<figure>
		{% if solution.client %}
		<a href="{% url 'clients:clients' %}#{{ solution.client.slug }}">
			<img src="{{ solution.client.logo.url }}" alt="{{ solution.client }}" height="60px" width="auto">
			<!-- <figcaption>Client logo</figcaption>      -->
			{% endif %}
		</a>
	</figure>
	{% endcomment %}
</main>
{% endblock content %}

templates/solutions/solution_details.html
{% extends "_base.html" %}
{% load i18n %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
 <h1>{% trans "Solutions" %}</h1> 
 <h2>[Client name]</h2> 
 <figure>
    <img src="https://placehold.co/250" alt="">
    <figcaption>Client logo</figcaption>
</figure>
<div>
   <h3>{% trans "Project description" %}</h3>
   <p>
      {% lorem %}
      {% lorem %} <br>
      {% lorem %}      
   </p>
</div>
<div>
   <h3>{% trans "Project gallery" %}</h3>
   <table>
      <tbody>
         {% for item in '12' %}
           
         <tr>
            {% for item in '1234' %}
            <td>
               <img src="https://placehold.co/250" alt="">
               <br>
               Sample project
               <br>              
               
            </td>
            {% endfor %}
         </tr>
         {% endfor %}
      </tbody>
   </table>
</div>

{% endblock content %}

templates/solutions/solutions.html
{% extends "_base.html" %}
{% load i18n static %}
{% block title %}{{ page_title }}{% endblock title %}

{% block content %}
<main class="main_solutions">

   <h1 class="main-title">
      
      {% if tag %}
      <span>
         <span class="mil-thin">{% trans "Tag" %}:</span>
      </span>{{ tag.name }}
                       
      {% else %}
      <span>
         <span class="mil-thin">our</span>
      </span>{% trans "Solutions" %}
      {% endif %}
   </h1>

   {% comment %}
   {% include "../components/btns/wg-down-inside.html" with title='solutions' link='solutions' %}
   {% endcomment %}
   
   {% for category in categories %}

      <section id="solutions">
         <!-- <div class="solutions_top"> -->
            <h2 class="main-title">               
               <span>{{ category }}
                  <span class="mil-thin"></span>
               </span>
            </h2>
            <!-- <a href="" class="btn btn-white no-rm">view all solutions<img src="{% static 'assets/g1b.svg' %}"></a> -->
         <!-- </div> -->

         <div class="solution_box">
            {% for solution in category.solutions.all %}
               {% include "solutions/_solution_card.html" %}
            {% endfor %}     
         </div>         
      </section>
            
   {% endfor %}
	
</main>
{% endblock content %}